package com.unac.serviciomvn.security.enums;

public enum RolNombre {
    ROLE_TECNICOS_TALLER, 
    ROLE_SUPERVISOR_TALLER,
    ROLE_ASISTENTE_RECURSOS_HUMANOS,
    ROLE_ASISTENTE_FINANCIERO,
    ROLE_GERENTE_FINANCIERO,
    ROLE_ASISTENTE_GERENCIA,
    ROLE_GERENTE_GENERAL,
    ROLE_INVITADO
}
